#!/bin/sh

set -eux
remote=https://github.com/nixos/nixpkgs.git
gitcache="$HOME/.cache/git-cache"
(
  mkdir -p "$gitcache"
  cd "$gitcache" || exit 1
  if [ ! -d ./nixpkgs ]; then
    git clone "$remote" ./nixpkgs
  fi

  cd nixpkgs || exit 1
  git remote set-url origin "$remote"
  git gc
  git fetch "origin"
)

if [ ! -d ./nixpkgs ]; then
  git clone --reference "$gitcache/nixpkgs" -- "$remote" ./nixpkgs
fi

calculate "$PWD/nixpkgs" "./data"

make-index ./data

git add ./data

if ! git diff --cached --exit-code; then
  git commit -m "Automatic channel data update."
  git push vaultpush HEAD:"$BUILDKITE_BRANCH"
fi

aws s3 sync ./data/ s3://channels.nix.gsc.io20210208030937774500000002 --delete --exclude '*.html' --no-guess-mime-type --content-type text/plain
aws s3 sync ./data/ s3://channels.nix.gsc.io20210208030937774500000002 --delete --exclude '*' --include '*.html' --no-guess-mime-type --content-type text/html
