#!/bin/sh

set - eux
remote=https://github.com/nixos/nixpkgs.git
if [ ! -d ./nixpkgs ]; then
  git clone "$remote" ./nixpkgs
fi

git -C ./nixpkgs remote set-url origin "$remote"

calculate "$PWD/nixpkgs" "./data"

git add ./data

if ! git diff --cached --exit-code; then
  git commit -m "Automatic channel data update."
  git push vaultpush HEAD:"$BUILDKITE_BRANCH"
fi
