#!/usr/bin/env bash

set -eu

cd "$1" || exit 1

enumerate_dir() (
    name=$1
    dir=$2

    printf "<h3><tt>%s</tt></h3>\n" "$(echo "$name" | recode ascii..html)"
    echo "<ul>"

    find "$dir" -mindepth 1 -maxdepth 1 -type f -print0 | sort -z -h -t- -k1 -k2 | while IFS="" read -d '' -r file; do
        printf '<li><tt><a href="%s">%s</a></tt></li>\n' "$(echo "$file" | recode ascii..html)" "$(basename "$file" | recode ascii..html)"
    done

    echo "</ul>"
)

enumerate_top_level() (
  find . -mindepth 1 -maxdepth 1 -type d -print0 | sort -z -h -t- -k1 -k2 -r | while IFS="" read -d '' -r dir; do
    enumerate_dir "$(basename "$dir")" "$dir"
  done
)

(
    enumerate_dir 'top level' '.'
    enumerate_top_level
    echo '<hr />source: <a href="https://github.com/grahamc/nix-channel-monitor">github.com/grahamc/nix-channel-monitor</a>'
) > ./index.html
